add colorEcho() add rfc as a standalone script

diff --git a/dot.bin/annotate b/dot.bin/annotate
--- a/dot.bin/annotate
+++ b/dot.bin/annotate
@@ -1,27 +1,50 @@
 #!/bin/bash
 
-[[ -n "$2" ]] || { cat <<EOF
-`basename $0` - Add text annotation into any type of image.
+usage(){
+	cat <<EOF
+`basename $0` - Add text annotation on any type of image.
 
-Usage: `basename $0` <Image> <text> [x,y] [font size]
+Usage: `basename $0` [-h] [-c x,y] [-f font size] <Image> <text>
 
-    Image - the image to be annotated
+    Image - the image to be annotated on
      text - text to be added
-      x,y - coordinate of text to be added, default to '+300+30'
-font size - default to 22
+       -c - coordinate of text to be added, default to '+300+30'
+       -f - default to 22
 EOF
-exit 4;
 }
 
-[[ -f "$1" ]] || { echo $1: 'Image file not found!'; exit 1; }
+#######color code########
+ERR="31m"     # red
+SUCCESS="32m" # green
+WARN="33m"    # yellow
+INFO="36m"    # blue
+
+colorEcho(){
+    echo -e "\033[${1}${@:2}\033[0m" 1>& 2
+}
+
+# defaults
+XY='+300+30'
+FS='22'
+
+while getopts :hf:c: OPT; do
+	case $OPT in
+		h) usage; exit 0 ;;
+		f) FS="$OPTARG" ;;
+		c) XY="$OPTARG" ;;
+		?) usage; exit 2
+	esac
+done
+shift $(( OPTIND - 1 ))
+OPTIND=1
 
 IMG="$1"
-TXT="$2"
-XY='+300+30'; [[ -n "$5" ]] && XY=$5
-FS='22'; [[ -n "$6" ]] && FS=$6
+[[ -f "$IMG" ]] || { colorEcho $ERR "Error: Image <$IMG> not found!"; usage; exit 1; }
 
-# https://tecadmin.net/how-to-extract-filename-extension-in-shell-script/
+TXT="$2"
+[[ -n "$TXT" ]] || { colorEcho $ERR 'Error: No annotation text!'; usage; exit 3; }
+
 BASE="${IMG%.*}"
 
 # convert -list font | grep CJK
-convert $IMG -pointsize $FS -font 'Noto-Sans-CJK-SC-Regular' -annotate $XY "$TXT" $BASE-anno.png
+convert $IMG -pointsize $FS -font 'Noto-Sans-CJK-SC' -annotate $XY "$TXT" $BASE-anno.png
diff --git a/dot.bin/pdfsign b/dot.bin/pdfsign
--- a/dot.bin/pdfsign
+++ b/dot.bin/pdfsign
@@ -13,8 +13,18 @@ EOF
     exit 4;
 }
 
+#######color code########
+ERR="31m"     # red
+SUCCESS="36m" # green
+WARN="32m"    # yellow
+INFO="34m"    # blue
+
+colorEcho(){
+    echo -e "\033[${1}${@:2}\033[0m" 1>& 2
+}
+
 do_check(){
-	[[ -f "$1" ]] || { echo 'Missing background PDF file!'; usage; }
+	[[ -f "$1" ]] || { colorEcho $ERR 'Error: Missing background PDF file!'; usage; }
 }
 
 do_init(){
@@ -95,16 +105,16 @@ EOF
 EOF
 }
 
-do_check $1 $2
+do_check $1
 do_init $@
 
 case "$GRID" in
 	g|grid)
-		echo "Signing with grid..."
+		colorEcho $INFO "Signing with grid..."
 		do_grid
 		;;
 	n|ng|nogrid)
-		echo "Signing without grid..."
+		colorEcho $INFO "Signing without grid..."
 		do_nogrid
 		;;
 	*)
@@ -112,11 +122,11 @@ case "$GRID" in
 		;;
 esac
 
-echo Signing <$BG>...
+colorEcho $INFO "Signing <$BG>..."
 xelatex $TEX > /dev/null
 
-[[ -f "$PDF" ]] || { echo Failed generating PDF file. Please check <$LOG> file for details; exit 5;}
+[[ -f "$PDF" ]] || { colorEcho $ERR "Failed generating PDF file. Please check <$LOG> file for details"; exit 5;}
 
-{ echo 'DONE!'; ls -l $PDF; }
+{ colorEcho $SUCCESS 'DONE!'; ls -l $PDF; }
 
 rm -f $AUX $LOG $TEX
diff --git a/dot.bin/pdfsign2 b/dot.bin/pdfsign2
--- a/dot.bin/pdfsign2
+++ b/dot.bin/pdfsign2
@@ -17,6 +17,16 @@ cleanup(){
 	rm -f $AUX $LOG $TEX
 }
 
+#######color code########
+ERR="31m"     # red
+SUCCESS="36m" # green
+WARN="32m"    # yellow
+INFO="34m"    # blue
+
+colorEcho(){
+    echo -e "\033[${1}${@:2}\033[0m" 1>& 2
+}
+
 grid(){
 	cat <<EOF >> $TEX
 \documentclass[tikz]{standalone}
@@ -104,7 +114,7 @@ shift $(( OPTIND - 1 ))
 OPTIND=1
 
 BG="$@"
-[[ -f "$BG" ]] || { echo "File <$BG> does not exist!"; exit 1; }
+[[ -f "$BG" ]] || { colorEcho $ERR "Error: File <$BG> does not exist!"; exit 1; }
 
 TEX="${BG%.pdf}-signed.tex"
 PDF="${TEX%.tex}.pdf"
@@ -113,20 +123,20 @@ AUX="${TEX%.tex}.aux"
 
 case "$GRID" in
 	g)
-		echo "Signing with grid..."
+		colorEcho $INFO "Signing with grid..."
 		grid
 		;;
 	ng)
-		echo "Signing without grid..."
+		colorEcho $INFO "Signing without grid..."
 		nogrid
 		;;
 esac
 
-echo Signing <$BG>...
+colorEcho $INFO "Signing <$BG>..."
 xelatex $TEX > /dev/null
 
-[[ -f "$PDF" ]] || { echo Failed generating PDF file. Please check <$LOG> file for details; exit 5;}
+[[ -f "$PDF" ]] || { colorEcho $ERR "Failed generating PDF file. Please check <$LOG> file for details"; exit 5;}
 
-{ echo 'DONE!'; ls -l $PDF; }
+{ colorEcho $SUCCESS 'DONE!'; ls -l $PDF; }
 
 
diff --git a/dot.bin/src2pdf b/dot.bin/src2pdf
--- a/dot.bin/src2pdf
+++ b/dot.bin/src2pdf
@@ -17,6 +17,17 @@ cleanup(){
 
 trap cleanup EXIT
 
+#######color code########
+ERR="31m"     # red
+SUCCESS="36m" # green
+WARN="32m"    # yellow
+INFO="34m"    # blue
+
+colorEcho(){
+    echo -e "\033[${1}${@:2}\033[0m" 1>& 2
+}
+#########################
+
 STYLE=default
 SCRATCH=$(mktemp -d)
 
@@ -47,7 +58,7 @@ for f in "$@"; do
 		pygmentize -f tex -O "style=$STYLE,linenos,full,preamble=$PREAMBLE" $f \
 			| xelatex -jobname=$(basename $f) -output-directory=$SCRATCH
 	else
-		echo "File <$f> not found." && exit 1
+		echo $ERR "Error: File <$f> not found." && exit 1
 	fi
 
 	[[ "$STYLE" = "default" ]] \
