rm shadowsocks-libev add .bin/grid

diff --git a/dot.bin/pdfsign b/dot.bin/pdfsign
--- a/dot.bin/pdfsign
+++ b/dot.bin/pdfsign
@@ -2,15 +2,27 @@
 
 usage(){
     cat <<EOF
-Usage: $(basename $0) '<background> <signature> [g|ng] [x,y] [scale] [year] [month] [date]'
+USAGE: $(basename $0) [-h] [-n] [-c x,y] [-w width] [-s s,t] [-t y,m,d] [-p x,y] [-S picture|text] <background>
 
-background - paper to sign on
- signature - signature file or text
-      g|ng - show grid or not
-       x,y - coordinate, e.g. '12,6', '1.1,y' for the last page
-     scale - scale to your signature (.2 looks good; 1.3 for the last page)
+EXAMPLES:
+1. $(basename $0) -c'12,6' -w25mm paper.pdf
+2. $(basename $0) -c'12,6' -s'1.4,.85' -t'2020,5,8' -p'15,6' -S'王晓林' paper.pdf
+3. $(basename $0) -c'12,6' -s'1.4,.85' -S'\purisa 2020\quad 5\qquad 8' paper.pdf
+
+background - paper to sign;
+        -h - help
+        -S - signature picture or text. Default='{.,..}/signature.pdf' if found;
+        -n - hide grid;
+        -c - coordinate of signature. Default='12,6';
+        -p - coordinate for year/month/date. Default='12,5';
+        -t - timestamp, e.g. '2020,5,8';
+        -w - width of signature picture. Default=25mm.
+        -s - scale of signature text and timestamp. Default='1.4,.85';
 EOF
-    exit 4;
+}
+
+cleanup(){
+	rm -f $AUX $LOG $TEXFILE
 }
 
 #######color code########
@@ -23,110 +35,140 @@ colorEcho(){
     echo -e "\033[${1}${@:2}\033[0m" 1>& 2
 }
 
-do_check(){
-	[[ -f "$1" ]] || { colorEcho $ERR 'Error: Missing background PDF file!'; usage; }
-}
-
-do_init(){
-	BG="$1"
-	SIG="$2"
-	GRID=${3:-'ng'}
-	XY=${4:-'12,6'}
-	SCALE=${5:-'.2'}
-	Y=${6:-''}
-	M=${7:-''}
-	D=${8:-''}
-
-	TEX="${BG%.pdf}-signed.tex"
-	PDF="${TEX%.tex}.pdf"
-	LOG="${TEX%.tex}.log"
-	AUX="${TEX%.tex}.aux"
-
-	rm -f $PDF $TEX
-}
-
-do_grid(){
-	cat <<EOF >> $TEX
+grid(){
+	cat <<EOF >> $TEXFILE
 \documentclass[tikz]{standalone}
 \usetikzlibrary{backgrounds}
 \usepackage[scheme=plain]{ctex}
 \newCJKfontfamily\sig{signature}
 \newfontfamily\purisa{Purisa}
 \begin{document}
-\begin{tikzpicture}[inner sep=0]
-    \node (bg) at (0,0) [anchor=south west]
-		 {\includegraphics[width=\paperwidth]{$BG}};
+\begin{tikzpicture}[inner sep=0,anchor=south west]
+    \node (bg) at (0,0) {\includegraphics[width=\paperwidth]{$BG}};
 
 	\begin{scope}
 	%%% grid
-	\draw[help lines,red,step=1] (0,0) grid (21,31);%
-	\foreach \x in {0,1,...,20} { \node [anchor=south] at (\x,0) {\x}; }%
-	\foreach \y in {0,1,...,30} { \node [anchor=west] at (0,\y) {\y}; }%
+	\draw[help lines,red,step=1] (0,0) grid (20,30);%
+	\foreach \x in {1,2,...,19} { \node at (\x,0) {\x}; }%
+	\foreach \y in {1,2,...,29} { \node at (0,\y) {\y}; }%
 EOF
 	if [[ -f "$SIG" ]]
-	then
-		# for first pages
-		echo "\node at ($XY) [scale=$SCALE,anchor=west] { \includegraphics{$SIG}};" >> $TEX
-	else
-		# for the last page
-		echo "\node at ($XY) [scale=$SCALE,anchor=west] {{\sig $SIG}{\purisa\hspace{31mm}{$Y}\hspace{3mm}\makebox[1em][c]{$M}\hspace{2mm}\makebox[1em][c]{$D}}};" >> $TEX
+	then # sign with a picture
+		echo "\node at ($XY) {\includegraphics[width=$WIDTH]{$SIG}};" >> $TEXFILE
+	else # sign with text
+		SIGSCALE=$(echo $SCALE | cut -d, -f1);
+		echo "\node at ($XY) [scale=$SIGSCALE] {{\sig $SIG}};" >> $TEXFILE
 	fi
-	cat <<EOF >> $TEX
+
+	[[ -n $TIMESTAMP ]] && {
+		Y=$(echo $TIMESTAMP | cut -d, -f1);
+		M=$(echo $TIMESTAMP | cut -d, -f2);
+		D=$(echo $TIMESTAMP | cut -d, -f3);
+		YMDSCALE=$(echo $SCALE | cut -d, -f2);
+		cat<<EOF >> $TEXFILE;
+\node at ($YMD)[scale=$YMDSCALE,fill=white] {\makebox[8.5em][s]{$Y 年 $M 月 $D 日}};
+EOF
+	}
+
+	cat <<EOF >> $TEXFILE
     \end{scope}
 	\end{tikzpicture}
 \end{document}
 EOF
 }
 
-do_nogrid(){
-	cat <<EOF >> $TEX
+nogrid(){
+	cat <<EOF >> $TEXFILE
 \documentclass[tikz]{standalone}
 \usetikzlibrary{backgrounds}
 \usepackage[scheme=plain]{ctex}
 \newCJKfontfamily\sig{signature}
 \newfontfamily\purisa{Purisa}
 \begin{document}
-\begin{tikzpicture}[inner sep=0]
-    \node (bg) at (0,0) [anchor=south west] {\includegraphics[width=\paperwidth]{$BG}};
+\begin{tikzpicture}[inner sep=0,anchor=south west]
+    \node (bg) at (0,0) {\includegraphics[width=\paperwidth]{$BG}};
 	\begin{scope}
 EOF
 	if [[ -f "$SIG" ]]
-	then
-		# for first pages
-		echo "\node at ($XY) [scale=$SCALE,anchor=west] { \includegraphics{$SIG}};" >> $TEX
-	else
-		# for the last page
-		echo "\node at ($XY) [scale=$SCALE,anchor=west] {{\sig $SIG}{\purisa\hspace{31mm}$Y\hspace{3mm}\makebox[1em][c]{$M}\hspace{2mm}\makebox[1em][c]{$D}}};" >> $TEX
+	then # sign with a picture
+		echo "\node at ($XY) {\includegraphics[width=$WIDTH]{$SIG}};" >> $TEXFILE
+	else # sign with text
+		SIGSCALE=$(echo $SCALE | cut -d, -f1);
+		echo "\node at ($XY) [scale=$SIGSCALE] {{\sig $SIG}};" >> $TEXFILE
 	fi
-	cat <<EOF >> $TEX
+
+	[[ -n $TIMESTAMP ]] && {
+		Y=$(echo $TIMESTAMP | cut -d, -f1);
+		M=$(echo $TIMESTAMP | cut -d, -f2);
+		D=$(echo $TIMESTAMP | cut -d, -f3);
+		YMDSCALE=$(echo $SCALE | cut -d, -f2);
+		cat<<EOF >> $TEXFILE;
+\node at ($YMD)[scale=$YMDSCALE,fill=white] {\makebox[8.5em][s]{$Y 年 $M 月 $D 日}};
+EOF
+	}
+	
+	cat <<EOF >> $TEXFILE
     \end{scope}
 	\end{tikzpicture}
 \end{document}
 EOF
 }
 
-do_check $1
-do_init $@
+trap cleanup EXIT
+
+# defaults
+[[ -e signature.pdf ]] && SIG='signature.pdf'
+[[ -e ../signature.pdf ]] && SIG='../signature.pdf'
+GRID='g'
+XY='12,6'
+YMD='7.05,16.15'
+WIDTH='25mm'
+SCALE='1.4,.85'
+TIMESTAMP=''
+Y=''
+M=''
+D=''
+
+while getopts :hnc:p:s:w:t:S: OPT; do
+	case $OPT in
+		h) usage; exit 0 ;;
+		n) GRID='ng' ;;
+		c) XY="$OPTARG" ;;
+		p) YMD="$OPTARG" ;;
+		s) SCALE="$OPTARG" ;;
+		w) WIDTH="$OPTARG" ;;
+		t) TIMESTAMP="$OPTARG" ;;
+		S) SIG="$OPTARG" ;;
+		?) usage; exit 2
+	esac
+done
+shift $(( OPTIND - 1 ))
+OPTIND=1
+
+BG="$@"
+[[ -f "$BG" ]] || { colorEcho $ERR "ERROR: <${BG:-BACKGROUND}> NOT FOUND."; usage; exit 1; }
+
+TEXFILE="${BG%.pdf}-signed.tex"
+PDF="${TEXFILE%.tex}.pdf"
+LOG="${TEXFILE%.tex}.log"
+AUX="${TEXFILE%.tex}.aux"
 
 case "$GRID" in
-	g|grid)
+	g)
 		colorEcho $INFO "Signing with grid..."
-		do_grid
+		grid
 		;;
-	n|ng|nogrid)
+	ng)
 		colorEcho $INFO "Signing without grid..."
-		do_nogrid
-		;;
-	*)
-		usage
+		nogrid
 		;;
 esac
 
 colorEcho $INFO "Signing <$BG>..."
-xelatex $TEX > /dev/null
+xelatex $TEXFILE > /dev/null
 
 [[ -f "$PDF" ]] || { colorEcho $ERR "Failed generating PDF file. Please check <$LOG> file for details"; exit 5;}
 
 { colorEcho $SUCCESS 'DONE!'; ls -l $PDF; }
 
-rm -f $AUX $LOG $TEX
+
diff --git a/dot.bin/utils b/dot.bin/utils
--- a/dot.bin/utils
+++ b/dot.bin/utils
@@ -1,43 +1,73 @@
 #!/bin/bash
 
 BROWSER="/usr/bin/x-www-browser"
-TIMETABLE="$HOME/texmf/doc/latex/swfu/timetable/timetable.pdf"
-MUPDF="/usr/bin/mupdf -r285"
-XPDF="/usr/bin/mupdf -r180"
+MUPDF="/usr/bin/mupdf -r285 -C FDF6E3"
+XPDF="/usr/bin/mupdf -r180 -C FDF6E3"
 ZATHURA="/usr/bin/zathura --fork"
 
-blp(){
-	($ZATHURA $HOME/Documents/Beginning.Linux.Programming-4e.pdf)
+v(){
+	select BOOK in \
+		"$HOME/lecture_notes/linux-app/slides/lap-a.pdf" \
+		"$HOME/lecture_notes/linux-app/slides/lap-b.pdf" \
+		"$HOME/lecture_notes/os/slides/os-a.pdf" \
+		"$HOME/lecture_notes/os/slides/os-b.pdf" \
+		"$HOME/lecture_notes/network_basics/net-a.pdf" \
+		"$HOME/lecture_notes/network_basics/net-b.pdf" \
+		"$HOME/lecture_notes/linux/linux_intro/linux_intro-b.pdf" \
+		"$HOME/Documents/Beginning.Linux.Programming-4e.pdf" \
+		"$HOME/Documents/network/ComputerNetworks-AST-5e.pdf" \
+		"$HOME/texmf/doc/latex/ch8.pdf" \
+		"/usr/share/doc/texlive-doc/generic/pgf/pgfmanual.pdf" \
+		"$HOME/texmf/doc/latex/symbols-a4.pdf" \
+		"$HOME/Documents/The.Linux.Programming.Interface.pdf" \
+		"$HOME/texmf/doc/latex/swfu/timetable/timetable.pdf" 
+	do
+		($MUPDF $BOOK &>/dev/null &)
+		break
+	done	
 }
 
-ch8(){
-    ($MUPDF ~/texmf/doc/latex/ch8.pdf &>/dev/null &)
+ffshot(){ # screenshot
+	ffmpeg -y -f x11grab -s 1920x1080 -r 1 -i $DISPLAY -vframes 1 /tmp/screenshot.jpg &>/dev/null
 }
 
-math(){
-    ($MUPDF ~/texmf/doc/latex/ch8.pdf &>/dev/null &)
+ffscreen(){ # capture screen lossy
+	ffmpeg -f x11grab -s 1920x1080 -r 25 -i :0.0 \
+		   -c:v libx264 -preset superfast \
+		   $(date +%Y%m%d%H%M).mp4
 }
 
-pgfmanual(){
-	($ZATHURA /usr/share/doc/texlive-doc/generic/pgf/pgfmanual.pdf &>/dev/null &)
+ffscreenlossless(){ # capture screen losslessly (very large file!)
+	ffmpeg -f x11grab -s 1920x1080 -r 30 -i :0.0 \
+		   -c:v libx264rgb -crf 0 -preset superfast \
+		   $(date +%Y%m%d%H%M).mkv
 }
 
-symbol(){
-    ($MUPDF ~/texmf/doc/latex/symbols-a4.pdf &>/dev/null &)
+mp4(){
+	ffmpeg -i $1 -c:v libx265 -preset ultrafast $1.mp4
 }
 
-tikz(){ pgfmanual; }
+ffoverlay(){ # capture screen and webcam
+	# man ffmpeg-filters
+	# use 'ffplay -f v4l2 -list_formats all /dev/video0' to check for available video_size
+	# 1280x720 960x540 848x480 640x480 640x360
 
-timetable(){
-	($MUPDF $TIMETABLE &>/dev/null &)
+	ffmpeg -f x11grab -s 1920x1080 -r 30 -i :0.0 \
+		   -f v4l2    -s 640x360   -r 25 -i /dev/video0 \
+		   -f alsa -i pulse \
+		   -filter_complex "overlay=W-w:H-h" \
+		   -map 2:a \
+		   -c:v libx265 -c:a aac -b:a 48k \
+		   $(date +%Y%m%d%H%M).mp4
 }
 
-tlpi(){
-	($ZATHURA $HOME/Documents/The.Linux.Programming.Interface.pdf)
-}
-
-screencapture(){
-	(ffmpeg -f x11grab -s 1920x1080 -r 30 -i :0.0 -c:v libx264 -crf 0 -preset ultrafast screen.mkv)
+ffwebcam(){ # capture webcam
+	# use 'ffplay -f v4l2 -list_formats all /dev/video0' to check for available video_size
+	
+	ffmpeg -f v4l2 -s 640x480 -r 30 -i /dev/video0 \
+		   -f alsa -i pulse \
+		   -c:v libx264 -preset superfast -qp 0 -c:a aac -b:a 48k \
+		   $(date +%Y%m%d%H%M).mp4
 }
 
 # http://superuser.com/questions/611538/is-there-a-way-to-display-a-countdown-or-stopwatch-timer-in-a-terminal
@@ -72,7 +102,7 @@ ec(){
     (/usr/bin/env emacsclient -t -a "" "$@")
 }
 
-ecw(){
+ee(){
 	emacsclient -n -e "(if (> (length (frame-list)) 1) 't)" | grep -q t
 	if [ "$?" = "1" ]; then
     	emacsclient -c -n -a "" "$@"
@@ -81,44 +111,22 @@ ecw(){
 	fi
 }
 
+ev(){
+	emacsclient -n -e "(if (> (length (frame-list)) 1) 't)" | grep -q t
+	if [ "$?" = "1" ]; then
+    	emacsclient -c -n -a "" --eval "(view-file \"$@\")" 
+	else
+   		emacsclient -n -a "" --eval "(view-file \"$@\")"
+	fi
+}
+
 # viewing markdown file in lynx
 mdview(){
 	(pandoc "$1" | lynx -stdin)
 }
 
-lapa(){
-	($ZATHURA $HOME/lecture_notes/linux-app/slides/lap-a.pdf)
-}
-
-lapb(){
-	($MUPDF $HOME/lecture_notes/linux-app/slides/lap-b.pdf &>/dev/null &)
-}
-
-linux(){
-	($MUPDF $HOME/lecture_notes/linux/linux_intro/linux_intro-b.pdf &>/dev/null &)
-}
-
-nerd(){
-	($ZATHURA $HOME/.local/share/fonts/truetype/nerd-fonts/dejavu/nerd.pdf)
-}
-neta(){
-	($ZATHURA $HOME/lecture_notes/network_basics/net-a.pdf)
-}
-
-netb(){
-	($MUPDF $HOME/lecture_notes/network_basics/net-b.pdf &>/dev/null &)
-}
-
-osa(){
-	($ZATHURA $HOME/lecture_notes/os/slides/os-a.pdf)
-}
-
-osb(){
-	($MUPDF $HOME/lecture_notes/os/slides/os-b.pdf &>/dev/null &)
-}
-
 pdf2gray(){
-	(gs -sOutputFile=gray.pdf -sDEVICE=pdfwrite -sColorConversionStrategy=Gray -dProcessColorModel=/DeviceGray -dCompatibiltyLevel=1.4 -dNOPAUSE -dBATCH $@)
+	gs -sOutputFile=gray.pdf -sDEVICE=pdfwrite -sColorConversionStrategy=Gray -dProcessColorModel=/DeviceGray -dCompatibiltyLevel=1.4 -dNOPAUSE -dBATCH $@
 }
 
 speak(){
@@ -129,9 +137,9 @@ speak(){
 	(/usr/bin/espeak -s 140 -v mb-us2 "$*";)
 }
 
-srtplay(){
-	(mplayer /dev/zero -demuxer rawvideo -rawvideo w=1024:h=128 -utf8 -sub "$*";)
-}
+# srtplay(){
+# 	mplayer /dev/zero -demuxer rawvideo -rawvideo w=1024:h=128 -utf8 -sub "$*";
+# }
 
 ssh() {
     if [ "$(ps -p $(ps -p $$ -o ppid=) -o comm=)" = "tmux" ]; then
@@ -221,11 +229,11 @@ done
 }
 
 themelight () {
-	(wal -q -l --theme tempus_dawn)
+	(wal -q -n -l --theme base16-atelier-plateau)
 }
 
 themedark () {
-	(wal -q --theme tempus_autumn)
+	(wal -q -n --theme tempus_autumn)
 }
 
 technotes () {
@@ -236,12 +244,21 @@ netnotes () {
 	(emacsclient -e '(progn (find-file-read-only-other-frame "~/lecture_notes/network_basics/net-tools/net-tools.org"))')
 }
 
-update-calibre () {
-	sudo -v && wget --no-check-certificate -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('$HOME/')"
+# update-calibre () {
+# 	sudo -v && wget --no-check-certificate -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('$HOME/')"
+# }
+
+pdf () {
+	# (libreoffice --convert-to pdf:writer_pdf_Export "$1")
+	libreoffice --headless --print-to-file $@
 }
 
-w2pdf () {
-	(libreoffice --convert-to pdf:writer_pdf_Export "$1")
+ppt () {
+	libreoffice --show $@
+}
+
+xls2x () { # xls -> xlsx
+	libreoffice --convert-to xlsx "$1"
 }
 
 xpdf(){
@@ -253,8 +270,12 @@ ydl(){
 	youtube-dl -f$fmt -o$1 $2
 }
 
-cs6movie(){
-	(aria2c --no-conf -x16 https://cs6.swfu.edu.cn/~wx672/tmp/$1)
+cs6a(){
+	(aria2c --no-conf -x16 https://cs6.swfu.edu.cn/~wx672/700/a/$1)
+}
+
+cs6v(){
+	(aria2c --no-conf -x16 https://cs6.swfu.edu.cn/~wx672/700/v/$1)
 }
 
 # https://madebynathan.com/2011/10/04/a-nicer-way-to-use-xclip/
