update

diff --git a/dot.bin/ssr b/dot.bin/ssr
--- a/dot.bin/ssr
+++ b/dot.bin/ssr
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-SSR="/home/wx672/.local/share/shadowsocksr/shadowsocks/local.py"
-SERVERDIR="/home/wx672/.local/share/fyvvv"
+SSR="$HOME/.local/share/shadowsocksr/shadowsocks/local.py"
+SERVERDIR="$HOME/.local/share/fyvvv"
 
 usage(){
 	cat <<EOF
@@ -24,7 +24,8 @@ shift $(( OPTIND - 1 ))
 OPTIND=1
 
 JSON="$@"
+echo "$JSON" | grep -q '\.' || JSON="$JSON".json
 
-[[ -f "$SERVERDIR/$JSON" ]] || { echo "ERROR: <${JSON:-json file}> not found in $SERVERDIR."; usage; exit 2; }
+[[ -f "$SERVERDIR/$JSON" ]] || { echo "ERROR: <$JSON> file not found in $SERVERDIR."; usage; exit 2; }
 
 $SSR -c $SERVERDIR/$JSON
