add pandoc template swfulabreport.latex

diff --git a/bin/.local/bin/clashy b/bin/.local/bin/clashy
--- a/bin/.local/bin/clashy
+++ b/bin/.local/bin/clashy
@@ -1,48 +1,47 @@
 #!/bin/bash
 
-cmdchk xsel yq || exit 127
+cmdchk yq || exit 127
 
 cfgDir="$HOME/.config/mihomo"
 SELFYML="$cfgDir/wx672.yaml"
 DEFAULTYML="$cfgDir/config.yaml"
 ymlDir="$cfgDir/yml"
-CLIPBOARD="$(xsel -bo)"
-PROXY_ENTRY=""
-PROXY_NAME="$CLIPBOARD"
+unset PROXY_NAME PROXY_ENTRY OUTFILE
 
-usage(){
-	cat <<EOF
+usage() {
+  cat <<EOF
 ${0##*/} - Tweaking clash config file.
 
 USAGE: 
-    ${0##*/} -h  # help
+    ${0##*/} -i [file.yaml] # insert a proxy entry into $SELFYML
 			    
-    ${0##*/} -i  # insert into $SELFYML
+    ${0##*/} -r [file.yaml] # remove a proxy entry from a yml file (default to $DEFAULTYML)
 			    
-    ${0##*/} -r  # remove from $DEFAULTYML
-			    
-    ${0##*/} -s  # search by proxy name
+    ${0##*/} -s [file.yaml] # search by proxy name
 
-    ${0##*/} [-o output.yaml] -t <newly downloaded yaml file>  # tweak newly downloaded yaml file
+    ${0##*/} [-o output.yaml] -t [newlydownloaded.yaml]  # tweak newly downloaded yaml file
 
-    - Before insert/remove an entry, you need to put its proxy name onto the clipboard first. To list all the proxy names, you can use yq:
-
-        \$ yq '.proxies[].name' config.yaml
-
-    - Prerequiesite: xsel, yq
+    - Prerequiesite: yq
 EOF
-	return
+  exit ${1:-0}
 }
 
-[ "$1" ] || { usage; exit; }
+    # - Before insert/remove an entry, you need to put its proxy name onto the clipboard first. To list all the proxy names, you can use yq:
 
-doublecheck(){
-	local YML="$1"
-	local MSG="$2"
-	
-	PROXY_ENTRY=$(NAME="$PROXY_NAME" yq '.proxies[] | select(.name == strenv(NAME))' "$YML")
+        # \$ yq '.proxies[].name' config.yaml
 
-	cat <<EOF
+[ "$1" ] || usage
+
+# doublecheck <SRC.yml> <DST.yml>
+# populate PROXY_NAME and PROXY_ENTRY
+doublecheck() {
+  local SRC="$1"
+  local DST="$2"
+  PROXY_NAME="$(yq '.proxies[].name' $SRC | sk -e10)"
+
+  PROXY_ENTRY=$(NAME="$PROXY_NAME" yq '.proxies[] | select(.name == strenv(NAME))' "$SRC")
+
+  cat <<EOF
 ---
 Name: $(echo $PROXY_NAME)
 Proxy entry:
@@ -50,137 +49,154 @@ $(echo $PROXY_ENTRY)
 ---
 EOF
 
-	[ -z "$PROXY_ENTRY" ] && { echo "yq: Proxy entry not found in ${YML}!"; exit 1; }
+  [ "$PROXY_ENTRY" ] || {
+    echo "[doublecheck] yq: Proxy entry not found in $SRC!"
+    exit
+  }
 
-	cat <<EOF
-$2
+  cat <<EOF
+$DST
 --- q to quit, any other key to continue ---
 EOF
 
-	while read -s -n1
-	do
-		case $REPLY in
-			q) exit ;;
-			*) break ;;
-		esac
-	done
+  while read -s -n1; do
+    case $REPLY in
+      q) exit ;;
+      *) break ;;
+    esac
+  done
 
-	return
+  return
 }
 
-insert(){
-	doublecheck "$DEFAULTYML" "Insert the above entry into ${SELFYML##*/}?"
-	
-	sed -i "/^proxies:$/a\  - $PROXY_ENTRY" $SELFYML || { echo 'sed: Failed appending!'; exit 1; }
-	yq '.proxies[0]' $SELFYML || { echo 'yq: Failed updating .proxies[0]!'; exit 1; }
+insert() {
+  local SRC=${1:-$DEFAULTYML}
+  local DST=${2:-$SELFYML}
 
-	yq -i '.proxy-groups[1].proxies = [.proxies[0].name] + .proxy-groups[1].proxies' \
-	   $SELFYML || {
-		echo 'yq: Failed updating .proxy-groups[1].proxies!';
-		exit 1;
-	}
+  doublecheck "$SRC" "Insert the above entry into ${DST##*/}?"
 
-	yq '.proxy-groups[1].proxies' $SELFYML || exit 1
+  sed -i "/^proxies:$/a\  - $PROXY_ENTRY" $DST || {
+    echo '[insert] sed: Failed appending!'
+    exit 1
+  }
+  yq '.proxies[0]' $DST || {
+    echo '[insert] yq: Failed updating .proxies[0]!'
+    exit 1
+  }
 
-	exit
+  yq -i '.proxy-groups[1].proxies = [.proxies[0].name] + .proxy-groups[1].proxies' \
+    $DST || {
+      echo '[insert] yq: Failed updating .proxy-groups[1].proxies!'
+      exit 1
+    }
+
+  yq '.proxy-groups[1].proxies' $DST || exit 1
+
+  exit
 }
 
-remove()
-{
-	local YML="$1"
-	
-	doublecheck "$YML" "Remove the above entry from ${YML##*/}?"
-	
-	NAME="$PROXY_NAME" \
-		yq -i 'del(.proxy-groups[].proxies[] | select(. == strenv(NAME)))' $YML || {
-		cat<<EOF
-yq failed:
+# remove <SRC.yaml>
+remove() {
+  local SRC="${1:-$DEFAULTYML}"
+
+  doublecheck "$SRC" "Remove the above entry from ${SRC##*/}?"
+
+  NAME="$PROXY_NAME" \
+    yq -i 'del(.proxy-groups[].proxies[] | select(. == strenv(NAME)))' $SRC || {
+      cat <<ERR
+[remove] yq.del() failed:
 
 NAME="$PROXY_NAME" \
-		yq -i 'del(.proxy-groups[].proxies[] | select(. == strenv(NAME)))' $YML
-EOF
-		exit 1
-	}
+		yq -i 'del(.proxy-groups[].proxies[] | select(. == strenv(NAME)))' $SRC
+ERR
+      exit 1
+    }
 
-	NAME="$PROXY_NAME" \
-		yq -i 'del(.proxies[] | select(.name == strenv(NAME)))' $YML || {
-		cat<<EOF
-yq failed:
+  NAME="$PROXY_NAME" \
+    yq -i 'del(.proxies[] | select(.name == strenv(NAME)))' $SRC || {
+      cat <<ERR
+[remove] yq.del() failed:
 
 NAME="$PROXY_NAME" \
-		yq -i 'del(.proxies[] | select(.name == strenv(NAME)))' $YML
-EOF
-		exit 1
-	}
+		yq -i 'del(.proxies[] | select(.name == strenv(NAME)))' $SRC
+ERR
+      exit 1
+  }
 
-	echo $YML is updated.
-	
-	tmux send-keys -t{top-right} C-c
+  echo $SRC is updated.
 
-	exit
+  # tmux send-keys -t{top-right} C-c
+
+  exit
 }
 
-tweak(){
-	local YML=${OUTFILE:="$(date +%m%d).yml"}
+# clashy [-o OUTFILE.yml] -t [/tmp/newlydownloaded.yaml]
+tweak() {
+  local SRC=${1:-$(/bin/ls /tmp/*.yaml | sk -e10)}
+  local DST=${OUTFILE:-"$ymlDir/$(date +%m%d).yml"}
 
-	if [ -f "$1" ]; then
-		mv "$1" "$ymlDir/$YML"
-		YML="$ymlDir/$YML"
-	else
-		echo File "$1" does not exist.
-		exit 1
-	fi
+  [[ -f "$SRC" ]] && mv "$SRC" "$DST" || {
+    echo File "$SRC" does not exist.
+    exit 1  
+  }
 
-	sed -i '/^#/d' $YML
+  sed -i '/^#/d' $DST
 
-	sed -i '1,/^proxies:/d' $YML
+  sed -i '1,/^proxies:/d' $DST
 
-	sed -i '1i port: 7890\nsocks-port: 7891\nallow-lan: true\nmode: Rule\nlog-level: info\nexternal-controller: 0.0.0.0:9090\nexternal-ui: /home/wx672/.config/mihomo/ui\ndns:\n  enabled: true\n  ipv6: true\n  listen: 127.0.0.1:8854\n  default-nameserver:\n    - 223.5.5.5\n    - 114.114.114.114\n    - 119.29.29.29\n    - 1.0.0.1\n  nameserver:\n    - https://doh.pub/dns-query\n    - https://dns.alidns.com/dns-query\n    - https://223.6.6.6/dns-query\n    - https://rubyfish.cn/dns-query\n    - https://dns.pub/dns-query\n  fallback-filter:\n    geoip: false\n    ipcidr:\n      - 240.0.0.0/4\n      - 0.0.0.0/32\nproxies:' $YML
+  sed -i '1i port: 7890\nsocks-port: 7891\nallow-lan: true\nmode: Rule\nlog-level: info\nexternal-controller: 0.0.0.0:9090\nexternal-ui: /home/wx672/.config/mihomo/ui\ndns:\n  enabled: true\n  ipv6: true\n  listen: 127.0.0.1:8854\n  default-nameserver:\n    - 223.5.5.5\n    - 114.114.114.114\n    - 119.29.29.29\n    - 1.0.0.1\n  nameserver:\n    - https://doh.pub/dns-query\n    - https://dns.alidns.com/dns-query\n    - https://223.6.6.6/dns-query\n    - https://rubyfish.cn/dns-query\n    - https://dns.pub/dns-query\n  fallback-filter:\n    geoip: false\n    ipcidr:\n      - 240.0.0.0/4\n      - 0.0.0.0/32\nproxies:' $DST
 
-	yq -i '.rules = ["DOMAIN-SUFFIX,debian.org,DIRECT", "DOMAIN-SUFFIX,fai-project.org,DIRECT", "DOMAIN-SUFFIX,qemu.org,DIRECT", "DOMAIN-SUFFIX,gnu.org,DIRECT", "DOMAIN-SUFFIX,winegame.net,DIRECT", "DOMAIN-SUFFIX,www.kmwatersupply.com,DIRECT", "DOMAIN-SUFFIX,www.playonlinux.com,DIRECT", "DOMAIN-SUFFIX,sketchviz.com,DIRECT", "DOMAIN-SUFFIX,deepinos.org,DIRECT", "DOMAIN-SUFFIX,overleaf.com,DIRECT", "DOMAIN-SUFFIX,moodle.org,DIRECT", "DOMAIN-SUFFIX,grammarly.com,DIRECT", "DOMAIN-SUFFIX,ixigua.com,DIRECT", "DOMAIN-SUFFIX,gitee.com,DIRECT", "DOMAIN-SUFFIX,wiki.archlinux.org,DIRECT", "DOMAIN-SUFFIX,www.gnupg.org,DIRECT"] + .rules' $YML
+  yq -i '.rules = ["DOMAIN-SUFFIX,debian.org,DIRECT", "DOMAIN-SUFFIX,fai-project.org,DIRECT", "DOMAIN-SUFFIX,qemu.org,DIRECT", "DOMAIN-SUFFIX,gnu.org,DIRECT", "DOMAIN-SUFFIX,winegame.net,DIRECT", "DOMAIN-SUFFIX,www.kmwatersupply.com,DIRECT", "DOMAIN-SUFFIX,www.playonlinux.com,DIRECT", "DOMAIN-SUFFIX,sketchviz.com,DIRECT", "DOMAIN-SUFFIX,deepinos.org,DIRECT", "DOMAIN-SUFFIX,overleaf.com,DIRECT", "DOMAIN-SUFFIX,moodle.org,DIRECT", "DOMAIN-SUFFIX,grammarly.com,DIRECT", "DOMAIN-SUFFIX,ixigua.com,DIRECT", "DOMAIN-SUFFIX,gitee.com,DIRECT", "DOMAIN-SUFFIX,wiki.archlinux.org,DIRECT", "DOMAIN-SUFFIX,www.gnupg.org,DIRECT"] + .rules' $DST
 
-	yq '.rules' $YML | head -15
+  yq '.rules' $DST | head -15
 
-	sed -i '/中国/d' $YML
+  sed -i '/中国/d' $DST
+  sed -i '/CN/d' $DST
 
-	ln -sf $YML $DEFAULTYML
+  ln -sf $DST $DEFAULTYML
 
-	ls -l $DEFAULTYML
+  ls -l $DEFAULTYML
 
-	exit	
+  exit
 }
 
-search(){
-	echo Searching for '['${PROXY_NAME}']' ...
-	local YML="$1"
-	local ENTRY=$(NAME="$PROXY_NAME" yq '.proxies[] | select(.name == strenv(NAME))' $YML)
+search() {
+  local SRC=${1:-"$DEFAULTYML"}
+  PROXY_NAME="$(yq '.proxies[].name' $SRC | sk -e10)"
+  local ENTRY=$(NAME="$PROXY_NAME" yq '.proxies[] | select(.name == strenv(NAME))' $SRC)
+  echo Searching for '['${PROXY_NAME}']' ...
 
-	[ "$ENTRY" ] && { echo $ENTRY | yq;	} || {
-		echo "yq: Proxy entry not found in ${YML}!";
-		exit 1;
-	}
+  [ "$ENTRY" ] && { echo $ENTRY | yq; } || {
+    echo '[search] yq: Proxy entry not found in' $SRC!
+    exit
+  }
 }
 
-while getopts :hirst:o: OPT; do
-	case $OPT in
-		i) insert
-		   ;;
-		r) shift $(( OPTIND - 1 ))
-		   OPTIND=1
-		   remove ${1:-"$DEFAULTYML"}
-		   ;;
-		s) shift $(( OPTIND - 1 ))
-		   OPTIND=1
-		   search ${1:-"$SELFYML"}
-		   ;;
-		t) tweak "$OPTARG"
-		   ;;
-		o) OUTFILE="$OPTARG"
-		   ;;
-		h) usage; exit
-		   ;;
-		*) usage; exit
-	esac
+while getopts :irsto: OPT; do
+  case $OPT in
+    i)
+      shift $((OPTIND - 1))
+      OPTIND=1
+      insert
+      ;;
+    r)
+      shift $((OPTIND - 1))
+      OPTIND=1
+      remove
+      ;;
+    s)
+      shift $((OPTIND - 1))
+      OPTIND=1
+      search
+      ;;
+    t)
+      shift $((OPTIND - 1))
+      OPTIND=1
+      tweak 
+      ;;
+    o)
+      OUTFILE="$OPTARG"
+      ;;
+    *) usage ;;
+  esac
 done
-# 
-# 
diff --git a/bin/.local/bin/cmdchk b/bin/.local/bin/cmdchk
--- a/bin/.local/bin/cmdchk
+++ b/bin/.local/bin/cmdchk
@@ -1,57 +1,74 @@
 #!/bin/bash
 
-err(){
-	echo "$1" is missing.
-	case "$1" in
-		amixer ) echo '(sudo apt install alsa-utils)'
-				 ;;
-		aria2c ) echo '(sudo apt install aria2)'
-				 ;;
-		choose ) echo '(https://github.com/theryangeary/choose)'
-				 ;;
-		convert|identify|mogrify) echo '(sudo apt install imagemagick)'
-								  ;;
-		fc-* ) echo '(sudo apt install fontconfig)'
-			   ;;
-		fd ) echo '(sudo apt install fd-find)'
-			 ;;
-		jless ) echo '(https://github.com/PaulJuliusMartinez/jless)'
-				;;
-		mdless|mdcat ) echo '(https://github.com/swsnr/mdcat)'
-					   ;;
-		nc ) echo '(sudo apt install netcat-openbsd)'
-			 ;;
-		pdfto* ) echo '(sudo apt install poppler-utils)'
-				 ;;
-		potrace|mkbitmap ) echo '(sudo apt install potrace)'
-						   ;;
-		p[pnba]mto*|*top[nabp]m) echo '(sudo apt install netpbm)'
-								 ;;
-		tiff2*|*2tiff) echo '(sudo apt install libtiff-tools)'
-					   ;;
-		*webp*) echo '(sudo apt install webp)'
-				;;
-		rg ) echo '(sudo apt install ripgrep)'
-			 ;;
-		sk ) echo '(https://github.com/lotabout/skim)'
-			 ;;
-		st ) echo '(aptitude show stterm)'
-			 ;;
-		uni ) echo '(https://github.com/arp242/uni)'
-			  ;;
-		x-www-browser ) 
-				  ;;
-		bat|blight|calibre|curl|dict|dzen2|emacs|espeak-ng|ffmpeg|ffplay|libreoffice|lloconv|mihomo|mosh|mpv|mupdf|picom|rofi|rsync|screenkey|sm|squashfuse|w3m|wmctrl|xdotool|xinput|xprop|xsel|yq|yt-dlp|zathura )
-			echo "(sudo apt install $1)"
-			;;
-		*) echo  "(apt-file search bin/$1)".
-			;;
-	esac
+err() {
+  echo "$1" is missing.
+  case "$1" in
+    amixer)
+      echo '(sudo apt install alsa-utils)'
+      ;;
+    aria2c)
+      echo '(sudo apt install aria2)'
+      ;;
+    choose)
+      echo '(https://github.com/theryangeary/choose)'
+      ;;
+    convert | identify | mogrify)
+      echo '(sudo apt install imagemagick)'
+      ;;
+    fc-*)
+      echo '(sudo apt install fontconfig)'
+      ;;
+    fd)
+      echo '(sudo apt install fd-find)'
+      ;;
+    jless)
+      echo '(https://github.com/PaulJuliusMartinez/jless)'
+      ;;
+    mdless | mdcat)
+      echo '(https://github.com/swsnr/mdcat)'
+      ;;
+    nc)
+      echo '(sudo apt install netcat-openbsd)'
+      ;;
+    pdfto*)
+      echo '(sudo apt install poppler-utils)'
+      ;;
+    potrace | mkbitmap)
+      echo '(sudo apt install potrace)'
+      ;;
+    p[pnba]mto* | *top[nabp]m)
+      echo '(sudo apt install netpbm)'
+      ;;
+    tiff2* | *2tiff)
+      echo '(sudo apt install libtiff-tools)'
+      ;;
+    *webp*)
+      echo '(sudo apt install webp)'
+      ;;
+    rg)
+      echo '(sudo apt install ripgrep)'
+      ;;
+    sk)
+      echo '(https://github.com/lotabout/skim)'
+      ;;
+    st)
+      echo '(aptitude show stterm)'
+      ;;
+    uni)
+      echo '(https://github.com/arp242/uni)'
+      ;;
+    x-www-browser) ;;
+    bat | blight | calibre | curl | dict | dzen2 | emacs | espeak-ng | ffmpeg | ffplay | libreoffice | lloconv | mihomo | mosh | mpv | mupdf | picom | rofi | rsync | screenkey | sm | squashfuse | w3m | wmctrl | xdotool | xinput | xprop | xsel | yq | yt-dlp | zathura)
+      echo "(sudo apt install $1)"
+      ;;
+    *)
+      echo "(apt-file search bin/$1)".
+      ;;
+  esac
 
-	return 127
+  exit 127
 }
 
 for app in "$@"; do
-	command -v $app &>/dev/null && exit 0 || { err $app; exit 127; }
+  command -v $app &>/dev/null && exit 0 || err $app
 done
-
diff --git a/bin/.local/bin/grid b/bin/.local/bin/grid
--- a/bin/.local/bin/grid
+++ b/bin/.local/bin/grid
@@ -2,7 +2,7 @@
 
 cmdchk convert identify || exit 127
 usage() {
-	cat <<EOF
+  cat <<EOF
 ${0##*/} - draw grid on a picture
 
 USAGE: ${0##*/} [-h] [-s 'x,y'] [-c color] [-o opacity] [-O outfile] infile
@@ -14,6 +14,8 @@ OPTIONS:
  -w width      stroke width. Default to 1
  -O outfile    default to '/tmp/grid.png'
 EOF
+
+exit ${1:-0}
 }
 
 #######color code########
@@ -22,26 +24,28 @@ SUCCESS="32m" # green
 WARN="33m"    # yellow
 INFO="36m"    # blue
 
-colorEcho(){
-    echo -e "\033[${1}${@:2}\033[0m" 1>& 2
+colorEcho() {
+  echo -e "\033[${1}${@:2}\033[0m" 1>&2
 }
 
-while getopts :hc:s:w:o:O: OPT; do
-	case $OPT in
-		h) usage; exit 0 ;;
-		s) SPACING="$OPTARG" ;; 
-		c) COLOR="$OPTARG" ;; 
-		o) OPACITY="$OPTARG" ;;
-		w) WIDTH="$OPTARG" ;;
-		O) OUTFILE="$OPTARG" ;;
-		?) usage; exit 2
-	esac
+while getopts :c:s:w:o:O: OPT; do
+  case $OPT in
+    s) SPACING="$OPTARG" ;;
+    c) COLOR="$OPTARG" ;;
+    o) OPACITY="$OPTARG" ;;
+    w) WIDTH="$OPTARG" ;;
+    O) OUTFILE="$OPTARG" ;;
+    *) usage ;;
+  esac
 done
-shift $(( OPTIND - 1 ))
+shift $((OPTIND - 1))
 OPTIND=1
 
 INFILE="$@"
-[[ -f "$INFILE" ]] || { colorEcho $ERR 'ERROR: NO INPUT FILE SPECIFIED!'; usage; exit 1; }
+[[ -f "$INFILE" ]] || {
+  colorEcho $ERR 'ERROR: NO INPUT FILE SPECIFIED!'
+  usage 1
+}
 
 # get image dimensions
 W=$(identify -format "%w" "$INFILE")
@@ -54,17 +58,15 @@ yinc=${SPACING#*,}
 
 # get string for drawing grid lines
 DRAWSTR=""
-for ((i=0; i<=$H; i+=yinc)); do
-	DRAWSTR="$DRAWSTR M 0,$i L $W,$i"
+for ((i = 0; i <= $H; i += yinc)); do
+  DRAWSTR="$DRAWSTR M 0,$i L $W,$i"
 done
 
-for ((i=0; i<=$W; i+=xinc)); do
-	DRAWSTR="$DRAWSTR M $i,0 L $i,$H"
+for ((i = 0; i <= $W; i += xinc)); do
+  DRAWSTR="$DRAWSTR M $i,0 L $i,$H"
 done
 
 # process image
 convert $INFILE -flatten -fill none -stroke ${COLOR:-red} -strokewidth ${WIDTH:-1} \
-		-draw "stroke-opacity ${OPACITY:-1} path '$DRAWSTR'" \
-		${OUTFILE:-/tmp/grid.png}
-
-
+  -draw "stroke-opacity ${OPACITY:-1} path '$DRAWSTR'" \
+  ${OUTFILE:-/tmp/grid.png}
diff --git a/bin/.local/bin/pbm2pdf b/bin/.local/bin/pbm2pdf
--- a/bin/.local/bin/pbm2pdf
+++ b/bin/.local/bin/pbm2pdf
@@ -17,6 +17,7 @@ Threshold - man mkbitmap for details
       x,y - coordinate of text to be added, default to '+300+30'
 font size - default to 22
 EOF
+	exit ${1:-0}
 }
 
 cleanup(){
@@ -36,27 +37,26 @@ colorEcho(){
 }
 
 MKBMP=$(command -v mkbitmap)
-TRACE=''
+unset TRACE
 
-while getopts :hixf:t:T:c:S:F: OPT; do
+while getopts :ixf:t:T:c:S:F: OPT; do
 	case $OPT in
-		h) usage; exit 0 ;;
 		i) MKBMP="$MKBMP -i" ;;
-		x) TRACE="yes" ;;
+		x) TRACE="y" ;;
 		f) F="$OPTARG" ;;
 		t) T="$OPTARG" ;;
 		T) TXT="$OPTARG" ;;
 		c) XY="$OPTARG" ;;
 		S) FS="$OPTARG" ;;
 		F) FN="$OPTARG" ;;
-		?) usage; exit 2
+		?) usage ;;
 	esac
 done
 shift $(( OPTIND - 1 ))
 OPTIND=1
 
 IMG="$@"
-[[ -f "$IMG" ]] || { colorEcho $ERR "Image <$IMG> not found!"; usage; exit 1; }
+[[ -f "$IMG" ]] || { colorEcho $ERR "Image <$IMG> not found!"; usage 1; }
 
 # https://tecadmin.net/how-to-extract-filename-extension-in-shell-script/
 BASE="${IMG%.*}"
diff --git a/bin/.local/bin/pdfsign b/bin/.local/bin/pdfsign
--- a/bin/.local/bin/pdfsign
+++ b/bin/.local/bin/pdfsign
@@ -2,40 +2,39 @@
 
 usage(){
     cat <<EOF
-USAGE: ${0##*/} [-hD] [-p pattern] [-c xshift,yshift] [-d ysep] [-w width] [-s scale] [-t y,m,d] [-S picture|text] <background>
+USAGE: ${0##*/} [-D] [-C] [-c xshift,yshift] [-d ysep] [-w width] [-s scale] [-t y,m,d] [-S picture|text] <background>
 
 EXAMPLES:
-1. ${0##*/} -p'签.*章' -t'2024,6,7' -S'mysig.pdf'  pg_0001.pdf
-   ${0##*/} -p'签.*章' -t'2024,6,7' -S'\sig 王晓林' pg_0002.pdf
+1. ${0##*/} -C -t'2024,6,7' -S'mysig.pdf'  pg_0001.pdf
+   ${0##*/} -C -t'2024,6,7' -S'\sig 王晓林' pg_0002.pdf
   
-2. ${0##*/} -p'考核方式' -S'开卷机试' -c'60,-2' -s .9 pg_0001-signed.pdf
+2. ${0##*/} -C -S'机试' -c'60,2' -s .9 pg_0001-signed.pdf
 
 3. ${0##*/} -w10cm -c'-20,-50' -S'../analysis-improve.pdf' os-analysis.pdf
-   ${0##*/} -p'考试形式' -S'开卷机试' -c'50,25' -d'110' -t'2023/,12/,25' os-analysis-signed.pdf
+   ${0##*/} -S'机试' -c'50,25' -d'110' -t'2023/,12/,25' os-analysis-signed.pdf
 
 
 background - paper to sign
-        -h - help
-		-D - Enable debugging outputs and grid
-		-p - search pattern
-
+				-D - Enable debugging outputs and grid
+				-C - Invoke getCoordinate
         -S - signature picture or text
-		   	 Default='{.,..}/wangxiaolin.pdf' if found
+				   	 Default='{.,..}/wangxiaolin.pdf' if found
 
         -c - 'xshift,yshift' 
-		   	 Default to '28,-18' in pt if signed with picture
-			 Default to '28,-25' in pt if signed with \sig font text
+				   	 Default to '28,-18' in pt if signed with picture
+						 Default to '28,-25' in pt if signed with \sig font text
 
-		-d - ysep, shift of the "date field". Default to 180pt
+				-d - ysep, shift of the "date field". Default to 180pt
 
         -t - timestamp, e.g. '2020,5,8'
         -w - width of signature picture. Default to '1cm'
         -s - scale of signature text. Default to '1'
 EOF
+	exit ${1:-0}
 }
 
 cleanup(){
-	[[ "$DEBUG" ]] || { rm -f "$AUX" "$LOG" "$TEXFILE" "$DEBUGFILE"; }
+	[[ "$DEBUG" ]] || { rm -f "$AUX" "$LOG" "$TEX" "$DBG"; }
 }
 
 #######color code########
@@ -50,25 +49,34 @@ colorEcho(){
 
 # pdftotext -tsv os-marks.pdf - | rg -N "签.*章" | head -1 | choose -o ',' 6 7
 # pdftotext -tsv os-marks.pdf - | rg -N "考试.*日" | head -1 | choose -o ',' 6 7
+
+# XY=$(pdftotext -tsv "$BG" - | \
+# 		 rg -N "$PATN" | head -1 | \
+# 		 choose -o ',' 6 7)
+# [[ "$XY" ]] || { colorEcho $ERR 'Failed to get coordinate (XY)!'; exit 1; }
+# X=${XY%,*}pt
+# Y=${XY##*,}pt
+# XY=( $(pdftotext -tsv $BG - | rg -N "$PATN" | choose 6 7) )
+
 getCoordinate(){
-	XY=$(pdftotext -tsv "$BG" - | \
-			 rg -N "$PATN" | head -1 | \
-			 choose -o ',' 6 7)
+	XY=( $(pdftotext -tsv $BG - | sk -e10 | choose 6 7) )
 
-	[[ -z "$XY" ]] && { colorEcho $ERR 'Failed to get coordinate (XY)!'; exit -1; }
+	(( ${#XY[@]} == 2 )) || return
 
-	X=${XY%,*}pt
-	Y=${XY##*,}pt
+	X=${XY[0]}pt
+	Y=${XY[1]}pt
 
 	[[ "$DEBUG" ]] && {
-		echo "XY = $XY" > $DEBUGFILE
-		echo "X = $X" >> $DEBUGFILE
-		echo "Y = $Y" >> $DEBUGFILE
-	}	
+		echo '[getCoordinate] XY:' $XY > $DBG
+		echo '[getCoordinate]  X:' $X >> $DBG
+		echo '[getCoordinate]  Y:' $Y >> $DBG
+	}
+
+	return
 }
 
 signit(){
-	cat <<EOF > "$TEXFILE"
+	cat <<EOF > "$TEX"
 \documentclass[tikz]{standalone}
 \usetikzlibrary{backgrounds,positioning}
 \usepackage[scheme=plain]{ctex}
@@ -82,10 +90,10 @@ signit(){
 	\begin{scope}
 EOF
 
-	[[ "$DEBUG" ]] && {
-		echo "Draw grid for debugging..." >> $DEBUGFILE
+	[[ $DEBUG ]] && {
+		echo '[signit] grid for debugging...' >> $DBG
 
-		cat <<EOF >> "$TEXFILE"
+		cat <<EOF >> "$TEX"
 		%%% grid
 		\draw[help lines,red,step=25pt] (0,0) grid (600pt,850pt);
 		\draw[thin] (0,0) rectangle (595pt,842pt); % a4: 595x842
@@ -95,52 +103,51 @@ EOF
 	}
 	
 	if [[ -f "$SIG" ]]
-	then # sign with the picture. $XY is from getCoordinate()
-		cat <<EOF >> "$TEXFILE"
-		\node (sig) at (${X:-550pt},${Y:-800pt}) [%
+	then # sign with picture. $XY is from getCoordinate()
+		cat <<EOF >> "$TEX"
+		\node (sig) at (${X:-96pt},${Y:-809.77pt}) [%
 			  xshift=${XSHIFT:-28}pt, yshift=${YSHIFT:--18}pt] {%
 			  \includegraphics[width=${WIDTH:-1cm}]{$SIG}};
 EOF
 	else # sign with text
-		cat <<EOF >> "$TEXFILE"
-		\node (sig) at (${X:-550pt},${Y:-800pt}) [%
+		cat <<EOF >> "$TEX"
+		\node (sig) at (${X:-96pt},${Y:-809.77pt}) [%
 			  xshift=${XSHIFT:-28}pt, yshift=${YSHIFT:--25}pt,%
 			  scale=${SIGSCALE:-1}] {$SIG};
 EOF
 	fi
 	[[ "$DEBUG" ]] && {
-		cat <<EOF >> $DEBUGFILE
-Signed with <$SIG>
-	   at (${X:-550pt},${Y:-800pt})
+		cat <<EOF >> $DBG
+[signit] Signed with $SIG
+	   (X,Y) = (${X:-96pt},${Y:-809.77pt})
 	   [xshift=${XSHIFT:-28}pt, yshift=${YSHIFT:--18}pt, scale=${SIGSCALE:-1}]
+													    yshift=${YSHIFT:--25}pt if signed with text
 	   Picture width=${WIDTH:-1cm} if signed with a picture
-
-	   yshift=${YSHIFT:--25}pt if signed with text
 EOF
 	}
 
 	[[ "$Year" ]] && {
-		cat<<EOF >> "$TEXFILE";
+		cat<<EOF >> "$TEX";
 		\node [right=${YSEP:-183}pt of sig, yshift=-3pt, font=\purisa] {%
 		  $Year\hspace{1.5em}%
 		  \makebox[1em][c]{$Month}\quad%
 		  \makebox[1em][c]{$Day}};%
 EOF
 		[[ "$DEBUG" ]] && {
-			cat <<EOF >> $DEBUGFILE
-<$Year,$Month,$Day> is added at offset: (${YSEP:-180}pt)
+			cat <<EOF >> $DBG
+[signit] <$Year,$Month,$Day> is added at offset: (${YSEP:-180}pt)
 EOF
 		}
 	}
 
-	cat <<EOF >> "$TEXFILE"
+	cat <<EOF >> "$TEX"
     \end{scope}
 	\end{tikzpicture}
 \end{document}
 EOF
 	[[ "$DEBUG" ]] && {
-		cat "$DEBUGFILE"
-		cat "$TEXFILE"
+		cat "$DBG"
+		cat "$TEX"
 	}
 }
 
@@ -150,17 +157,17 @@ trap cleanup EXIT
 [[ -e wangxiaolin.pdf ]] && SIG='wangxiaolin.pdf'
 [[ -e ../wangxiaolin.pdf ]] && SIG='../wangxiaolin.pdf'
 
-unset X Y XY XSHIFT YSHIFT YSEP MSEP DSEP DEBUG SCALE WIDTH PATN
+unset X Y XY XSHIFT YSHIFT YSEP MSEP DSEP DEBUG SCALE WIDTH
 
-while getopts :hDc:d:p:s:w:t:S: OPT; do
+while getopts :DCc:d:s:w:t:S: OPT; do
 	case $OPT in
-		h) usage; exit 0 ;;
-		D) DEBUG='YES' ;;
+		D) DEBUG='Y' ;;
+		C) GETCOORDINATE='Y' ;;
 		c) XSHIFT=${OPTARG%,*}
 		   YSHIFT=${OPTARG#*,}
 		   ;;
 		d) YSEP="$OPTARG" ;;
-		p) PATN="$OPTARG" ;;
+		# p) PATN="$OPTARG" ;;
 		s) SIGSCALE="$OPTARG" ;;
 		w) WIDTH="$OPTARG" ;;
 		t) Year=${OPTARG%%,*}
@@ -168,7 +175,7 @@ while getopts :hDc:d:p:s:w:t:S: OPT; do
 		   Day=${OPTARG##*,}
 		   ;;
 		S) SIG="$OPTARG" ;;
-		?) usage; exit 2
+		?) usage 1 ;;
 	esac
 done
 shift $(( OPTIND - 1 ))
@@ -176,22 +183,23 @@ OPTIND=1
 
 BG="$*"
 
-[[ -f "$BG" ]] || { colorEcho $ERR "ERROR: <${BG:-BACKGROUND}> NOT FOUND."; usage; exit 1; }
+[[ -f "$BG" ]] || { colorEcho $ERR "ERROR: <${BG:-BACKGROUND}> NOT FOUND."; usage 2; }
 
-DEBUGFILE="__DEBUG__"; > $DEBUGFILE
-TEXFILE="${BG%.pdf}-signed.tex"; > $TEXFILE
-PDF="${TEXFILE%.tex}.pdf"
-LOG="${TEXFILE%.tex}.log"
-AUX="${TEXFILE%.tex}.aux"
+DBG="__DEBUG__"; > $DBG
+TEX="${BG%.pdf}-signed.tex"; > $TEX
+PDF="${TEX%.tex}.pdf"
+LOG="${TEX%.tex}.log"
+AUX="${TEX%.tex}.aux"
 
-[[ "$PATN" ]] && getCoordinate
+[[ $GETCOORDINATE ]] && getCoordinate
+# otherwise sign with default coordinate
 
 signit
 
-[[ "$DEBUG" ]] && echo "Signing <$BG>..." >> $DEBUGFILE
+[[ "$DEBUG" ]] && echo '[DEBUG] Signing '$BG'...' >> $DBG
 
-colorEcho $INFO "lualatex $TEXFILE..."
-lualatex "$TEXFILE" 1>/dev/null
+colorEcho $INFO "lualatex $TEX..."
+lualatex "$TEX" 1>/dev/null
 
 [[ -f "$PDF" ]] || { colorEcho $ERR "Failed generating PDF file. Please check <$LOG> file for details"; exit 5;}
 
diff --git a/bin/.local/bin/utils b/bin/.local/bin/utils
--- a/bin/.local/bin/utils
+++ b/bin/.local/bin/utils
@@ -1,334 +1,395 @@
 #!/bin/bash
 
-skemoji()
+skcht() 
 {
-	cmdchk uni sk xsel choose || return 1
+	CHTDIR="$HOME/.config/cheat/cheatsheets/personal"
+	SKOPTS="-e10 --preview-window=right:90%" 
 
-	[[ "$2" ]] || { echo usage: "skemoji <search|emoji> <search string>"; return 1; }
-
-	CMD="$1"
-	case $CMD in
-		s*) chosen=$(uni -quiet \
-						 -f "%(char l:3)%(wide_padding)%(cpoint l:8)%(name t)(%(block t))" \
-						 search "$2" | sk --exact \
-										  --select-1 \
-										  --exit-0 | choose 0)
-			;;
-		e*) chosen=$(uni -quiet emoji ${2:-all} | sort --random-sort | sk -e10 | choose 0)
-			;;
-		*) echo usage: "$0 <search|emoji> <search string>"; return 1
-		   ;;
-	esac
-
-	[ "$chosen" ] || return
-
-	printf "$chosen\n" && { xsel -bi <<<$chosen; }
-	# xdotool type "$chosen"
-	# notify-send "'$chosen' copied to clipboard."
-}
-
-skplay(){
-	cmdchk sk fd || return 1
-
-	sk < <(fd -d 1 -e mp4 -e mkv -e webm -e m4a -e mp3 -e rmvb -e avi -e flv "$1") \
-	   --exact --bind "enter:execute(mpv {})+abort"
-	
-	return 0
-}
-
-gmaps(){
-	QUERY=""
-	for WORD in "$@"; do
-		QUERY="$QUERY%20$WORD"
-	done
-	(x-www-browser https://www.google.com/maps/search/$QUERY 2>/dev/null &)
-}
-
-ffshot(){ # screenshot
-	cmdchk ffmpeg || return 1
-
-	ffmpeg -y -f x11grab -s 1920x1080 -r 1 -i "$DISPLAY" -vframes 1 /tmp/"$(date +%Y%m%d%H%M)".jpg &>/dev/null
-}
-
-ffrec(){ # screen recording lossy
-	cmdchk ffmpeg screenkey || return 1
-
-    trap 'pkill screenkey' INT EXIT TERM ERR
-
-
-    (screenkey --no-systray --opacity .3 --font-color red --font "Fira Code SemiBold" &)
-    
-	ffmpeg -f x11grab -s 1920x1080 -r 25 -i :0.0 \
-		   -c:v libx264 -preset superfast \
-		   "$(date +%Y%m%d%H%M)".mp4
-}
-
-ffrec_lossless(){ # screen recording losslessly (very large file!)
-	cmdchk ffmpeg || return 1
-
-	ffmpeg -f x11grab -s 1920x1080 -r 30 -i :0.0 \
-		   -c:v libx264rgb -crf 0 -preset superfast \
-		   "$(date +%Y%m%d%H%M)".mkv
-}
-
-mp4(){ # convert $1 to mp4
-	cmdchk ffmpeg || return 1
-
-	#  -preset ultrafast
-	ffmpeg -i "$1" -an -c:v libx265 "$1".mp4
-}
-
-ffrec_overlay(){ # recording screen and webcam
-	cmdchk ffmpeg || return 1
-
-	# man ffmpeg-filters
-	# use 'ffplay -f v4l2 -list_formats all /dev/video0' to check for available video_size
-	# 1280x720 960x540 848x480 640x480 640x360
-
-	ffmpeg \
-		-f x11grab -framerate 30 \
-		-s "$(xdpyinfo | awk '/dimensions/ {print $2;}')" \
-		-i "$DISPLAY" \
-		-f alsa -i pulse \
-		-f v4l2 -s 640x360 -framerate 30 -i /dev/video0 \
-		-filter_complex "overlay=W-w:H-h" \
-		-c:v libx264 -crf 0 -preset ultrafast -c:a aac -b:a 48k \
-		"$(date +%Y%m%d%H%M)".mp4
-}
-
-ffcam(){ # capture webcam
-	cmdchk ffmpeg || return 1
-
-	# use 'ffplay -f v4l2 -list_formats all /dev/video0' to check for available video_size
-	#  -preset superfast
-	ffmpeg -f v4l2 -s 640x480 -r 30 -i /dev/video0 \
-		   -f alsa -i hw:1 \
-		   -c:v libx264 -qp 0 -c:a aac -b:a 48k \
-		   "$(date +%Y%m%d%H%M)".mp4
-}
-
-dict () {
-	cmdchk dict bat || return 1
-	
-	(/usr/bin/dict "$@" 2>&1 | bat;)
-}
-
-e(){
-	cmdchk wmctrl emacs || return 1
-	# if emacsclient -e "(if (> (length (frame-list)) 1) 't)" | /bin/grep -q t; then
-	if wmctrl -xa emacs; then
-		[ "$1" ] && emacsclient -n "$@" || emacsclient -ne "(recentf-open-files)"
-	else
-		[ "$1" ] && emacsclient -nc "$@" || emacsclient -nce "(recentf-open-files)"
-	fi
-}
-
-emacs() { 
-	e "$@"; 
-}
-
-say(){
-	cmdchk espeak-ng || return 1
-
-	while getopts :v: OPT; do
-		case $OPT in
-			v) voice="$OPTARG" ;;
-			*) echo "Usage: espeak-ng [-h] [-v <voice>] words"; return 0 ;;
+	[[ $2 ]] && {
+		chosen=$(sk < <(/bin/ls $CHTDIR | rg $2) $SKOPTS \
+					--preview='cheat {} | mdless' )
+	} || {
+		case $1 in
+			-* | '')     
+				chosen=$(sk < <(/bin/ls $CHTDIR) $SKOPTS \
+					--preview='cheat {} | mdless' )
+				;;
+			*)
+				chosen=$(sk < <(/bin/ls $CHTDIR | rg $1) $SKOPTS \
+					--preview='cheat {} | mdless' )
+				;;
 		esac
-	done
-	shift $(( OPTIND - 1 ))
-	OPTIND=1
+	}
 	
-	($SAY -s140 -p70 -v${voice:="en-gb"}  "$*";)
+	[ $chosen ] || return
+
+	[[ $1 = -* ]] && cheat $1 $chosen || mdless <(cheat $chosen)
 }
 
-propstring () {
-	cmdchk xprop || return 1
+# skhst() {
+# 	sk < <(history) --tac --no-sort -m \
+# 	   --header='Select one or more entries:' \
+# 	   --prompt='DELETE: ' | choose 0 | xargs sh -c 'history -d'
+# }
 
-	echo -n 'Property '
-	xprop WM_CLASS | sed 's/.*"\(.*\)", "\(.*\)".*/= "\1,\2" {/g'
-	echo '}'
+skemj() {
+  cmdchk uni sk choose || return 127
+
+  [[ "$2" ]] || {
+    echo usage: "skemoji <search|emoji> <search string>"
+    return 1
+  }
+
+  case "$1" in
+    s*)
+      chosen=$(uni -quiet \
+        -f "%(char l:3)%(wide_padding)%(cpoint l:8)%(name t)(%(block t))" \
+        search "$2" | sk -e10 | choose 0)
+      ;;
+    e*)
+      chosen=$(uni -quiet emoji ${2:-all} | sort --random-sort | sk -e10 | choose 0)
+      ;;
+    *)
+      echo usage: "$0 <search|emoji> <search string>"
+      return 1
+      ;;
+  esac
+
+  [ "$chosen" ] || {
+    echo No match found.
+    return
+  }
+
+  tmux set-buffer -w "$chosen" && {
+    echo "$chosen is on clipboard."
+  }
 }
 
-booksearch () {
-	cmdchk calibre || return 1
+skplay() {
+  cmdchk sk fd || return 127
 
-	LIBPATH=$HOME/Calibre
+  sk < <(fd -d 1 --size +50m $1) \
+      --exact --bind "enter:execute(mpv {})+abort"
 
-	[[ "$1" ]] || { echo Usage: 'booksearch <keywords>'; return 1; }
-	calibredb list -s "$@" --with-library="$LIBPATH"/Calibre1
-	calibredb list -s "$@" --with-library="$LIBPATH"/Calibre2
-	calibredb list -s "$@" --with-library="$LIBPATH"/Calibre3
+  return
 }
 
-searchbook () {
-    (booksearch "$1")
+skpath() {
+  tmux set-buffer -w $(fd -a $1 | sk -e10)
+  echo '['$(tmux showb)']' is on clipboard.
 }
 
-pdf () {
-	cmdchk lloconv || return 1
-	local F="$1"
-    lloconv -f pdf "$F" "${F%.*}.pdf"
+realp() { 
+  skpath $1 
 }
 
-loconvert () {
-	cmdchk libreoffice || return 1
-	[ $1 ] || { echo 'Usage: locovert <to format> <source file>'; return 1; }
-	[ -f $2 ] || {
-		cat <<EOF
+gmaps() {
+  local QUERY=""
+  for WORD in "$@"; do
+    QUERY="$QUERY%20$WORD"
+  done
+  setsid -f x-www-browser https://www.google.com/maps/search/$QUERY 2>/dev/null
+}
+
+ffshot() { # screenshot
+  cmdchk ffmpeg || return 127
+
+  ffmpeg -y -f x11grab -s 1920x1080 -r 1 -i "$DISPLAY" -vframes 1 /tmp/"$(date +%Y%m%d%H%M)".jpg &>/dev/null
+}
+
+ffrec() { # screen recording lossy
+  cmdchk ffmpeg screenkey || return 127
+
+  trap 'pkill screenkey' INT EXIT TERM ERR
+
+  (screenkey --no-systray --opacity .3 --font-color red --font "Fira Code SemiBold" &)
+
+  ffmpeg -f x11grab -s 1920x1080 -r 25 -i :0.0 \
+    -c:v libx264 -preset superfast \
+    "$(date +%Y%m%d%H%M)".mp4
+}
+
+ffrec_lossless() { # screen recording losslessly (very large file!)
+  cmdchk ffmpeg || return 127
+
+  ffmpeg -f x11grab -s 1920x1080 -r 30 -i :0.0 \
+    -c:v libx264rgb -crf 0 -preset superfast \
+    "$(date +%Y%m%d%H%M)".mkv
+}
+
+mp4() { # convert $1 to mp4
+  cmdchk ffmpeg || return 127
+
+  #  -preset ultrafast
+  ffmpeg -i "$1" -an -c:v libx265 "$1".mp4
+}
+
+ffrec_overlay() { # recording screen and webcam
+  cmdchk ffmpeg || return 127
+
+  # man ffmpeg-filters
+  # use 'ffplay -f v4l2 -list_formats all /dev/video0' to check for available video_size
+  # 1280x720 960x540 848x480 640x480 640x360
+
+  ffmpeg \
+    -f x11grab -framerate 30 \
+    -s "$(xdpyinfo | awk '/dimensions/ {print $2;}')" \
+    -i "$DISPLAY" \
+    -f alsa -i pulse \
+    -f v4l2 -s 640x360 -framerate 30 -i /dev/video0 \
+    -filter_complex "overlay=W-w:H-h" \
+    -c:v libx264 -crf 0 -preset ultrafast -c:a aac -b:a 48k \
+    "$(date +%Y%m%d%H%M)".mp4
+}
+
+ffcam() { # capture webcam
+  cmdchk ffmpeg || return 127
+
+  # use 'ffplay -f v4l2 -list_formats all /dev/video0' to check for available video_size
+  #  -preset superfast
+  ffmpeg -f v4l2 -s 640x480 -r 30 -i /dev/video0 \
+    -f alsa -i hw:1 \
+    -c:v libx264 -qp 0 -c:a aac -b:a 48k \
+    "$(date +%Y%m%d%H%M)".mp4
+}
+
+dict() {
+  cmdchk dict bat || return 127
+
+  batcat <(/usr/bin/dict "$@")
+}
+
+e() {
+  cmdchk wmctrl emacs || return 127
+  # if emacsclient -e "(if (> (length (frame-list)) 1) 't)" | /bin/grep -q t; then
+  if wmctrl -xa emacs; then
+    [ "$1" ] && emacsclient -n "$@" || emacsclient -ne "(recentf-open-files)"
+  else
+    [ "$1" ] && emacsclient -nc "$@" || emacsclient -nce "(recentf-open-files)"
+  fi
+}
+
+emacs() {
+  e "$@"
+}
+
+say() {
+  cmdchk espeak-ng || return 127
+
+  while getopts :v: OPT; do
+    case $OPT in
+      v) voice="$OPTARG" ;;
+      *)
+        echo "Usage: espeak-ng [-h] [-v <voice>] words"
+        return 0
+        ;;
+    esac
+  done
+  shift $((OPTIND - 1))
+  OPTIND=1
+
+  ($SAY -s140 -p70 -v${voice:="en-gb"} "$*")
+}
+
+propstring() {
+  cmdchk xprop || return 127
+
+  echo -n 'Property '
+  xprop WM_CLASS | sed 's/.*"\(.*\)", "\(.*\)".*/= "\1,\2" {/g'
+  echo '}'
+}
+
+booksearch() {
+  cmdchk calibre || return 127
+
+  LIBPATH=$HOME/Calibre
+
+  [[ "$1" ]] || {
+    echo Usage: 'booksearch <keywords>'
+    return 1
+  }
+  calibredb list -s "$@" --with-library="$LIBPATH"/Calibre1
+  calibredb list -s "$@" --with-library="$LIBPATH"/Calibre2
+  calibredb list -s "$@" --with-library="$LIBPATH"/Calibre3
+}
+
+searchbook() {
+  (booksearch "$1")
+}
+
+pdf() {
+  cmdchk lloconv || return 127
+  local F="$1"
+  lloconv -f pdf "$F" "${F%.*}.pdf"
+}
+
+loconvert() {
+  cmdchk libreoffice || return 127
+  [ $1 ] || {
+    echo 'Usage: locovert <to format> <source file>'
+    return 1
+  }
+  [ -f $2 ] || {
+    cat <<EOF
 File not found.
 Usage: locovert <to format> <source file>
 EOF
-		return 1
-	}
-	libreoffice --headless --convert-to "$*"
+    return 1
+  }
+  libreoffice --headless --convert-to "$*"
 }
 
-ppt () {
-	cmdchk libreoffice || return 1
-	libreoffice --show "$*"
+ppt() {
+  cmdchk libreoffice || return 127
+  libreoffice --show "$*"
 }
 
-xls2x () { # xls -> xlsx
-	cmdchk libreoffice || return 1
-	libreoffice --convert-to xlsx "$1"
+xls2x() { # xls -> xlsx
+  cmdchk libreoffice || return 127
+  libreoffice --convert-to xlsx "$1"
 }
 
-sssh(){
-	cmdchk mosh || return 1
-	local KEY=""
-	local USR=""
-	local REMOTE=""
-	
-	while getopts :k:u:r: OPT; do
-		case $OPT in
-			k) KEY="--ssh=\"ssh -i $OPTARG\"" ;;
-			u) USR="$OPTARG" ;;
-			r) REMOTE="$OPTARG" ;;
-			h)
-				echo "Usage: sssh [-k key] [-u user] [-r remote-host]";
-				return 0 ;;
-			*)
-				echo "Usage: sssh [-k key] [-u user] [-r remote-host]";
-				return 1 ;;
-		esac
-	done
-	shift $(( OPTIND - 1 ))
-	OPTIND=1
+sssh() {
+  cmdchk mosh || return 127
+  local KEY=""
+  local USR=""
+  local REMOTE=""
 
-	[[ $1 = syk* ]] && REMOTE="sykp100.duckdns.org"
-	
-	[ $DISPLAY ] && {
-		cmdchk st || return 1
-		(st -e mosh ${KEY} ${USR:-wx672}@${REMOTE:-cs6.swfu.edu.cn} &)
-	} || {
-		mosh ${KEY} ${USR:-wx672}@${REMOTE:-cs6.swfu.edu.cn}
-	}
+  while getopts :k:u:r: OPT; do
+    case $OPT in
+      k) KEY="--ssh=\"ssh -i $OPTARG\"" ;;
+      u) USR="$OPTARG" ;;
+      r) REMOTE="$OPTARG" ;;
+      *)
+        echo "Usage: sssh [-k key] [-u user] [-r remote-host]"
+        return
+        ;;
+    esac
+  done
+  shift $((OPTIND - 1))
+  OPTIND=1
+
+  [[ $1 = syk* ]] && REMOTE="sykp100.duckdns.org"
+
+  [ $DISPLAY ] && {
+    cmdchk st || return 127
+    setsid -f st -e mosh ${KEY} ${USR:-wx672}@${REMOTE:-cs6.swfu.edu.cn}
+  } || {
+    mosh ${KEY} ${USR:-wx672}@${REMOTE:-cs6.swfu.edu.cn}
+  }
 }
 
-rcb () { # remote clipboard
-    cmdchk nc xsel || return 1
+rcb() { # remote clipboard
+  cmdchk nc || return 127
 
-    local PORT=${1:-33333}
+  local PORT=${1:-33333}
 
-    echo fetching from port "$PORT" ...
+  echo fetching from port $PORT ...
 
-    # at remote side (cs6) do, for example, 'ls *.mkv | nc -4l 33333'
-    { nc -4 cs6 "$PORT" || echo nc failed.; } | xsel -bi
-
-    xsel -bo
+  # at remote side (cs6) do, for example, 'ls *.mkv | nc -4l 33333'
+  tmux set-buffer -w $(nc -4 cs6 $PORT) || echo copy from nc failed.
+  tmux showb
 }
 
-cs6v(){
-	cmdchk aria2c xsel || return 1
-    url="https://cs6.swfu.edu.cn/~wx672"
-    base=${1:-tmp}
-    movies=$(xsel -bo)
+cs6v() {
+  cmdchk aria2c || return 127
 
-	[[ "$movies" ]] || { echo "Empty clipboard. Quit..."; return 1;	}
-	
-    cat <<EOF
+  local PORT=${1:-33333}
+  local url="https://cs6.swfu.edu.cn/~wx672"
+  local base=${1:-tmp}
+  local movies=$(nc -4 -w 1 cs6 $PORT)
+
+  [[ "$movies" ]] || {
+    echo "Movies are missing!"
+    return 1
+  }
+
+  cat <<EOF
 Files to be downloaded:
 
 $movies
 
 EOF
 
-    for m in $movies; do
-        echo Downloading "$url"/"$base"/"$m" ...
-        aria2c --no-conf --check-certificate=false -x16 "$url"/"$base"/"$m"
-    done    
+  for m in $movies; do
+    echo Downloading "$url"/"$base"/"$m" ...
+    aria2c --no-conf --check-certificate=false -x16 "$url"/"$base"/"$m"
+  done
 }
 
-cs6r(){
-	cmdchk rsync || return 1
-	rsync -avLP --inplace --append cs6:public_html/"$1" .
+cs6r() {
+  cmdchk rsync || return 127
+  rsync -avLP --inplace --append cs6:public_html/"$1" .
 }
 
-mdcheat(){
-	cmdchk mdless || return 1
-	mdless <(cheat $1)
+mdcht() {
+  cmdchk mdless || return 127
+  [[ $1 = -* ]] && cheat $@ || mdless <(cheat $@)
 }
 
-mount.sqfs(){
-	cmdchk squashfuse || return 1
-	mkdir -p "$1" && squashfuse "$1".sqfs "$1" && cd "$1"
+
+# mount.sqfs() {
+#   cmdchk squashfuse || return 127
+#   mkdir -p "$1" && squashfuse "$1".sqfs "$1" && cd "$1"
+# }
+
+mount.sqfs() {
+  cmdchk squashfs-mount || return 127
+  squashfs-mount ${1}:/mnt -- bash -c "cd /mnt && bash"
 }
 
 # https://stackoverflow.com/questions/660613/how-do-you-hide-the-mouse-pointer-under-linux-x11
-setmouse () {
-	cmdchk xinput || return 1
+setmouse() {
+  cmdchk xinput || return 127
 
-	for i in $(DISPLAY=":0" xinput | grep Mouse | cut -d"=" -f2 | cut -b-2)
-	do
-		DISPLAY=":0" xinput --"$1" "$i"
-	done
+  for i in $(DISPLAY=":0" xinput | grep Mouse | cut -d"=" -f2 | cut -b-2); do
+    DISPLAY=":0" xinput --"$1" "$i"
+  done
 }
 
-moff () {
-	cmdchk xdotool || return 1
-	DISPLAY=":0" xdotool mousemove 3840 2160 # use xrandr to find out
-	setmouse disable
+moff() {
+  cmdchk xdotool || return 127
+  DISPLAY=":0" xdotool mousemove 3840 2160 # use xrandr to find out
+  setmouse disable
 }
 
-mon () {
-	cmdchk xdotool || return 1
-	DISPLAY=":0" xdotool mousemove 1366 768 # use xrandr to find out
-	setmouse enable
+mon() {
+  cmdchk xdotool || return 127
+  DISPLAY=":0" xdotool mousemove 1366 768 # use xrandr to find out
+  setmouse enable
 }
 
 settouchpad() {
-	cmdchk xinput || return 1
+  cmdchk xinput || return 127
 
-	for i in $(DISPLAY=":0" xinput | grep Touchpad | cut -d"=" -f2 | cut -b-2)
-	do
-		DISPLAY=":0" xinput --"$1" "$i"
-	done
+  for i in $(DISPLAY=":0" xinput | grep Touchpad | cut -d"=" -f2 | cut -b-2); do
+    DISPLAY=":0" xinput --"$1" "$i"
+  done
 }
 
-toff () { # touchpad
-	cmdchk xdotool || return 1
-	DISPLAY=":0" xdotool mousemove 3840 2160 # use xrandr to find out
-	settouchpad disable
+toff() { # touchpad
+  cmdchk xdotool || return 127
+  DISPLAY=":0" xdotool mousemove 3840 2160 # use xrandr to find out
+  settouchpad disable
 }
 
-ton () {
-	cmdchk xdotool || return 1
-	DISPLAY=":0" xdotool mousemove 1366 768 # use xrandr to find out
-	settouchpad enable
+ton() {
+  cmdchk xdotool || return 127
+  DISPLAY=":0" xdotool mousemove 1366 768 # use xrandr to find out
+  settouchpad enable
 }
 
-loremipsum () {
-	cmdchk curl || return 1
-	if [ "${1}" = "" ] || [ "${2}" = "" ]; then
-		echo "Usage: loremipsum <paragraphs|sentences> <integer>"
-	else
-		curl -s http://metaphorpsum.com/"${1}"/"${2}" && printf "\n"
-	fi
+loremipsum() {
+  cmdchk curl || return 127
+  if [ "${1}" = "" ] || [ "${2}" = "" ]; then
+    echo "Usage: loremipsum <paragraphs|sentences> <integer>"
+  else
+    curl -s http://metaphorpsum.com/"${1}"/"${2}" && printf "\n"
+  fi
 }
 
-proxy () {
-	cat <<EOF
+proxy() {
+  cat <<EOF
 	pon/poff - Switch on/off proxy
 
 	Current settings:
@@ -337,22 +398,20 @@ proxy () {
 EOF
 }
 
-poff ()
-{
-	echo -n 'unset http_proxy HTTP_PROXY https_proxy HTTPs_PROXY... '
-    unset http_proxy HTTP_PROXY https_proxy HTTPs_PROXY
-	echo done.
+poff() {
+  echo -n 'unset http_proxy HTTP_PROXY https_proxy HTTPs_PROXY... '
+  unset http_proxy HTTP_PROXY https_proxy HTTPs_PROXY
+  echo done.
 }
 
-pon ()
-{
-	echo Turn on proxy...
-    http_proxy=http://127.0.0.1:${1:-1081}/
-    HTTP_PROXY=$http_proxy
-    https_proxy=$http_proxy
-    HTTPS_PROXY=$https_proxy
-    export http_proxy https_proxy HTTP_PROXY HTTPS_PROXY
-	cat <<EOF
+pon() {
+  echo Turn on proxy...
+  http_proxy=http://127.0.0.1:${1:-7890}/
+  HTTP_PROXY=$http_proxy
+  https_proxy=$http_proxy
+  HTTPS_PROXY=$https_proxy
+  export http_proxy https_proxy HTTP_PROXY HTTPS_PROXY
+  cat <<EOF
 	http_proxy=$http_proxy
 	HTTP_PROXY=$http_proxy
 	https_proxy=$http_proxy
